name: auto-publish-articles

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  env-install:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Branch
        uses: actions/checkout@v2.4.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "18.2.0"

      - name: Setup Express environment
        run: |
          npm i pnpm -g
          pnpm i  
